[project]
name = 'Pollution-Credit-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Pollution-Credit-Marketplace]
path = 'contracts/Pollution-Credit-Marketplace.clar'
clarity_version = 3
epoch = 3.1

[contracts.credit-bundler]
path = 'contracts/credit-bundler.clar'
clarity_version = 3
epoch = 3.1

[contracts.credit-price-oracle]
path = 'contracts/credit-price-oracle.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
